## Numpy crash course

In [2]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

In [6]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

## Creating Array

In [16]:
my_list=[0,1,2,3,4,5]

In [20]:
my_list

[0, 1, 2, 3, 4, 5]

In [22]:
type(my_list)

list

## Converting list to array below

In [27]:
#!pip install numpy if you work in vs code.

In [29]:
arr=np.array(my_list)

In [31]:
arr

array([0, 1, 2, 3, 4, 5])

In [33]:
type(arr)

numpy.ndarray

In [35]:
type(my_list)

list

In [39]:
# np. #we lwarn important functions.

In [41]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
np.arange(3.0)

array([0., 1., 2.])

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [49]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
np.arange(20,10) #1st argument < 2nd argument

array([], dtype=int32)

In [53]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [55]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [57]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [59]:
np.arange(30,20) #1st arg always be < then 2nd arg.

array([], dtype=int32)

In [61]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [63]:
np.arange(10,10)

array([], dtype=int32)

In [65]:
np.arange() #required argumeent.

TypeError: arange() requires stop to be specified.

In [68]:
np.arange(10,30,5) #start from 10 end from 30 and step count id 5

array([10, 15, 20, 25])

In [70]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [72]:
np.arange(10,30,5,8) #4 AGUMENT not allowed.

TypeError: Cannot interpret '8' as a data type

In [74]:
np.zeros(3) #parameter tunning.

array([0., 0., 0.])

parameter tunning - ststem default givr the parameter.

hyperparameter tunning - user wanted to change system parameter.

In [77]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [79]:
np.zeros(5,dtype=int)  #hyperparameter tunning. bydefault output is float is converted onto integer.

array([0, 0, 0, 0, 0])

In [81]:
np.zeros((2,2), dtype=int) #Two Dimension Array.

array([[0, 0],
       [0, 0]])

In [83]:
zero=np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [85]:
np.zeros((2,10)) #two brackets necessary for 2d arrays.

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [87]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [89]:
np.zeros((5,10),dtype=int) #bydefault large--will give row & 2nd  arg --columns.

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [91]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [93]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [95]:
n=(6,7)
n1=(6,8)
print(np.zeros(n1)) #parameter tunning.

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [97]:
print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [101]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [107]:
n= (5,7)
n1 = (6,8)
print(np.zeros(n)) # parameter tunning
#print(np.zeros(n1,dtype=int)) ## hypyerparameter tunning 

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [109]:
np.ones(3)

array([1., 1., 1.])

In [111]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [113]:
np.ones(4)

array([1., 1., 1., 1.])

In [117]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [119]:
np.ones((5,4),dtype=int) #bydefault 5 is row and 4 is a column.

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [123]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [127]:
np.ones(4)

array([1., 1., 1., 1.])

In [129]:
n

(5, 7)

In [131]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [133]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [135]:
np.two(4) #two is not inbuild function of numpy

AttributeError: module 'numpy' has no attribute 'two'

In [137]:
np.three(4) #three is not inbuild function of numpy

AttributeError: module 'numpy' has no attribute 'three'

In [139]:
random.rand #definee random 
rand(3,2)

NameError: name 'random' is not defined

In [143]:
np.random.rand(5) #5 random numbers creating.

array([0.85863988, 0.65338046, 0.06281003, 0.87443101, 0.84936361])

In [145]:
np.rand(4) #this code shows error because 'random' module is missing

AttributeError: module 'numpy' has no attribute 'rand'

In [147]:
np.random.rand(3,5)  #3 rows and 5 columns with different different numbers.numbers are float type

array([[0.3119542 , 0.75723254, 0.5697902 , 0.67129881, 0.04071654],
       [0.41474351, 0.79038566, 0.21070615, 0.80733046, 0.34860541],
       [0.35431155, 0.89581048, 0.90581655, 0.4379937 , 0.98721749]])

In [149]:
np.random.randint(2,4) #eturn random integers numbers.numbers are integer type

3

In [151]:
np.random.randint(4,6)

5

In [153]:
np.random.randint(2,20) #2nd argument is exclusive.

14

In [155]:
np.random.randint(0,1)

0

In [157]:
np.random.randint(10,20,5)

array([17, 19, 19, 16, 15])

In [159]:
np.random.randint(1,6,4) 

array([1, 2, 2, 5])

In [161]:
np.random.randint(3) 

1

In [163]:
np.random.randint(1) 

0

In [165]:
np.random.randint(30,20,10)  #Error because low >= high

ValueError: low >= high

In [167]:
np.random.randint(-30,20,10)  #Run because low >= high

array([ -7,  -5, -27, -22,  10,   0,  -7,  -5,  -7, -17])

In [169]:
np.random.randint(20,30,10)  

array([20, 24, 21, 23, 29, 21, 26, 26, 27, 27])

In [171]:
np.random.randint(5,9)  #Get the value <=1 >=5

6

In [173]:
np.random.randint(10,21,3) 

array([15, 19, 18])

In [175]:
np.random.randint(1,12,10) 

array([ 7,  5,  5,  3, 11,  3,  9,  5,  3,  4])

In [177]:
np.random.randint(10,40,(10,10)) #generate the element 10 -30 with 4*4 matrix.

array([[12, 11, 39, 10, 11, 11, 12, 12, 33, 24],
       [29, 33, 31, 19, 26, 25, 25, 31, 32, 24],
       [37, 21, 27, 30, 38, 25, 15, 35, 34, 19],
       [33, 31, 21, 28, 20, 16, 20, 25, 23, 11],
       [16, 35, 24, 34, 12, 14, 38, 13, 14, 23],
       [30, 15, 18, 39, 39, 15, 19, 38, 30, 30],
       [18, 18, 31, 24, 15, 14, 37, 16, 39, 20],
       [20, 33, 25, 31, 29, 24, 25, 33, 22, 15],
       [37, 31, 36, 13, 21, 17, 12, 34, 24, 22],
       [33, 15, 10, 10, 14, 28, 39, 28, 27, 26]])

In [179]:
np.random.randint(1,100,(12,12)) #generate the element 1 100 with 4*4 matrix.

array([[49, 92, 98, 38, 64, 40, 64, 55, 26, 73,  6, 70],
       [77, 81, 29,  9, 12, 24, 37, 58, 33, 20, 38, 88],
       [21, 63, 29, 62, 92, 31,  9,  2,  1, 32, 88, 17],
       [ 2, 59, 89, 47, 76, 58, 88,  6, 52,  9, 89, 43],
       [88, 83, 18, 59, 36, 91,  1, 42, 85, 48, 88, 90],
       [50,  9, 54, 74, 71, 86,  7, 60, 47, 97,  1, 18],
       [18, 98, 25, 51, 95, 93, 76, 26, 81, 69,  4, 83],
       [12, 23, 78, 98, 66, 75, 33, 17, 49, 27, 44, 38],
       [96, 10, 24, 54, 98, 59, 45, 58, 84, 66, 89,  5],
       [74, 38, 99, 50, 13, 45, 81, 71,  3, 20, 28, 17],
       [73, 61, 44, 40, 43, 47, 51, 36, 15, 13, 26, 96],
       [83, 62, 14, 59, 26,  6, 14, 20, 11, 20, 44, 86]])

In [181]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [183]:
np.arange(1,13).reshape(5,4) #cannot reshape array of size 12 into shape (5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [185]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [187]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [189]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [191]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

## Slicing in matrix

In [194]:
b=np.random.randint(10,20,(5,4)) #5 rows 4 col
b

array([[13, 17, 14, 12],
       [17, 16, 12, 16],
       [19, 18, 11, 18],
       [10, 17, 18, 17],
       [11, 19, 12, 15]])

In [196]:
type(b)

numpy.ndarray

In [198]:
b

array([[13, 17, 14, 12],
       [17, 16, 12, 16],
       [19, 18, 11, 18],
       [10, 17, 18, 17],
       [11, 19, 12, 15]])

In [200]:
b[:]

array([[13, 17, 14, 12],
       [17, 16, 12, 16],
       [19, 18, 11, 18],
       [10, 17, 18, 17],
       [11, 19, 12, 15]])

In [202]:
b[1:3] #slicing is there so n-1 formulae is applicable.

array([[17, 16, 12, 16],
       [19, 18, 11, 18]])

In [204]:
b[1,2] #according to index 1 row 2 col

12

In [206]:
b[1,3]

16

In [208]:
b[2:3]

array([[19, 18, 11, 18]])

In [210]:
b[0:-2]

array([[13, 17, 14, 12],
       [17, 16, 12, 16],
       [19, 18, 11, 18]])

In [212]:
b[0:2]

array([[13, 17, 14, 12],
       [17, 16, 12, 16]])

In [214]:
b

array([[13, 17, 14, 12],
       [17, 16, 12, 16],
       [19, 18, 11, 18],
       [10, 17, 18, 17],
       [11, 19, 12, 15]])

In [216]:
b[-5,-3]

17

In [218]:
np.random.randint(10,20,(4,4))

array([[14, 18, 16, 12],
       [17, 15, 16, 17],
       [17, 16, 10, 11],
       [15, 14, 16, 10]])

In [220]:
b

array([[13, 17, 14, 12],
       [17, 16, 12, 16],
       [19, 18, 11, 18],
       [10, 17, 18, 17],
       [11, 19, 12, 15]])

In [222]:
b[-4,-2]

12

In [224]:
b[:]

array([[13, 17, 14, 12],
       [17, 16, 12, 16],
       [19, 18, 11, 18],
       [10, 17, 18, 17],
       [11, 19, 12, 15]])

## Operations

In [227]:
a=np.random.randint(10,20,10)
a

array([15, 12, 17, 19, 13, 11, 17, 17, 15, 19])

In [229]:
id(a)

2167057857776

In [231]:
arr

array([0, 1, 2, 3, 4, 5])

In [233]:
arr2=np.random.randint(0,100,(10,10))

In [235]:
arr2

array([[11, 94, 29, 72, 13, 86,  3, 64, 48, 57],
       [89, 99, 69, 15, 28, 20, 49, 97, 50, 26],
       [79, 43, 23, 99, 45, 27,  4,  7, 42, 54],
       [87, 28, 34, 14, 49, 95, 69, 55, 38, 82],
       [ 0, 78, 21, 18, 18, 46, 84, 74, 51, 54],
       [33, 50,  2, 94, 19, 81, 55, 64, 65, 55],
       [57, 45,  9, 78, 22, 56, 56, 14, 51,  0],
       [94, 27, 93, 85, 29, 74, 64, 84, 67, 83],
       [61, 66, 31, 52, 73, 75,  4, 66, 65, 57],
       [42,  4, 28, 30,  2, 99, 38, 12, 61, 20]])

In [237]:
arr2[::-1]

array([[42,  4, 28, 30,  2, 99, 38, 12, 61, 20],
       [61, 66, 31, 52, 73, 75,  4, 66, 65, 57],
       [94, 27, 93, 85, 29, 74, 64, 84, 67, 83],
       [57, 45,  9, 78, 22, 56, 56, 14, 51,  0],
       [33, 50,  2, 94, 19, 81, 55, 64, 65, 55],
       [ 0, 78, 21, 18, 18, 46, 84, 74, 51, 54],
       [87, 28, 34, 14, 49, 95, 69, 55, 38, 82],
       [79, 43, 23, 99, 45, 27,  4,  7, 42, 54],
       [89, 99, 69, 15, 28, 20, 49, 97, 50, 26],
       [11, 94, 29, 72, 13, 86,  3, 64, 48, 57]])

In [239]:
arr2

array([[11, 94, 29, 72, 13, 86,  3, 64, 48, 57],
       [89, 99, 69, 15, 28, 20, 49, 97, 50, 26],
       [79, 43, 23, 99, 45, 27,  4,  7, 42, 54],
       [87, 28, 34, 14, 49, 95, 69, 55, 38, 82],
       [ 0, 78, 21, 18, 18, 46, 84, 74, 51, 54],
       [33, 50,  2, 94, 19, 81, 55, 64, 65, 55],
       [57, 45,  9, 78, 22, 56, 56, 14, 51,  0],
       [94, 27, 93, 85, 29, 74, 64, 84, 67, 83],
       [61, 66, 31, 52, 73, 75,  4, 66, 65, 57],
       [42,  4, 28, 30,  2, 99, 38, 12, 61, 20]])

In [241]:
arr2[::-2] #step count

array([[42,  4, 28, 30,  2, 99, 38, 12, 61, 20],
       [94, 27, 93, 85, 29, 74, 64, 84, 67, 83],
       [33, 50,  2, 94, 19, 81, 55, 64, 65, 55],
       [87, 28, 34, 14, 49, 95, 69, 55, 38, 82],
       [89, 99, 69, 15, 28, 20, 49, 97, 50, 26]])

In [243]:
arr2[::-3]

array([[42,  4, 28, 30,  2, 99, 38, 12, 61, 20],
       [57, 45,  9, 78, 22, 56, 56, 14, 51,  0],
       [87, 28, 34, 14, 49, 95, 69, 55, 38, 82],
       [11, 94, 29, 72, 13, 86,  3, 64, 48, 57]])

In [245]:
arr2

array([[11, 94, 29, 72, 13, 86,  3, 64, 48, 57],
       [89, 99, 69, 15, 28, 20, 49, 97, 50, 26],
       [79, 43, 23, 99, 45, 27,  4,  7, 42, 54],
       [87, 28, 34, 14, 49, 95, 69, 55, 38, 82],
       [ 0, 78, 21, 18, 18, 46, 84, 74, 51, 54],
       [33, 50,  2, 94, 19, 81, 55, 64, 65, 55],
       [57, 45,  9, 78, 22, 56, 56, 14, 51,  0],
       [94, 27, 93, 85, 29, 74, 64, 84, 67, 83],
       [61, 66, 31, 52, 73, 75,  4, 66, 65, 57],
       [42,  4, 28, 30,  2, 99, 38, 12, 61, 20]])

In [247]:
arr.max()

5

In [249]:
arr.min()

0

In [251]:
arr.mean()

2.5

In [253]:
from numpy import*
a=array([1,2,3,4,9])
median(a)

3.0

In [255]:
arr

array([0, 1, 2, 3, 4, 5])

In [257]:
arr.reshape(2,3)  

array([[0, 1, 2],
       [3, 4, 5]])

In [259]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [261]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [263]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [265]:
arr

array([0, 1, 2, 3, 4, 5])

In [267]:
arr.reshape(1,5) #Gives ValueError

ValueError: cannot reshape array of size 6 into shape (1,5)

In [269]:
arr.reshape(3,2,order='C') 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [271]:
arr.reshape(3,2,order='F') 

array([[0, 3],
       [1, 4],
       [2, 5]])

In [273]:
arr.reshape(3,2,order='A') 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [275]:
arr.reshape(3,2,order='K') #ValueError

ValueError: order 'K' is not permitted for reshaping

In [277]:
arr

array([0, 1, 2, 3, 4, 5])

In [279]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [281]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [283]:
arr.reshape(6,1) 

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [293]:
arr.reshape(3,3) #ValueError

ValueError: cannot reshape array of size 6 into shape (3,3)

In [289]:
arr

array([0, 1, 2, 3, 4, 5])

In [291]:
arr.reshape(3,2) 

array([[0, 1],
       [2, 3],
       [4, 5]])

## Indexing

In [306]:
mat = np.arange(0,100).reshape(10,10)

In [308]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [310]:
row = 4
col = 5

In [312]:
col

5

In [314]:
row

4

In [316]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [318]:
mat[row,col] 

45

In [320]:
mat[4,5] 

45

In [322]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [324]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [326]:
col = 6

In [328]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [330]:
# With Slices
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [332]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [334]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [336]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [338]:
row

4

In [340]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [342]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [344]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [346]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [348]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [350]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [352]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [354]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [356]:
row

4

In [358]:
col

6

In [360]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [362]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [364]:
mat[1,4]

14

In [368]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [370]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [372]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [374]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [376]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [378]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [380]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [382]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [384]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [386]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [388]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [390]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [392]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [394]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [396]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [398]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [400]:
mat[1:2,2:4]

array([[12, 13]])

In [402]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [404]:
mat[2:3,2:3]

array([[22]])

In [406]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [408]:
mat[3:5,2:4,]

array([[32, 33],
       [42, 43]])

In [410]:
mat[2:3,4:5]

array([[24]])

## Masking

In [413]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [415]:
id(mat)

2167058179984

In [417]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [419]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [421]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [423]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [425]:
mat[mat==50] 

array([50])

In [427]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [429]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [431]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [433]:
a3 = mat[mat>=50] 
a3

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [435]:
a4 = mat[mat==50]
a4

array([50])

In [437]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [439]:
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])